version: "3.8"

services:
  app:
    image: instrument-hub:latest # Or you can use 'build: .' to build the image locally
    container_name: instrument-hub
    volumes:
      - instrument-hub:/app/data # Mount the named volume to the /app/data directory
    ports:
      - "9000:9000"
    environment:
      - ENVIRONMENT=production
      - DB_TYPE=postgresql
      - DB_USER=postgres
      - DB_PASSWORD=example
      - DB_NAME=instrument_hub_db
      - DB_ADDRESS=db:5432 # Referencing the Postgres service by name and port
    restart: always
    depends_on:
      - db # Ensures that the db service starts before the app service

  db:
    image: postgres
    container_name: instrument-hub-db
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: instrument_hub_db
    volumes:
      - instrument-hub-db:/var/lib/postgresql/data # Persist Postgres data

volumes:
  instrument-hub: # Define the named volume for app data
  instrument-hub-db: # Define a named volume for Postgres data
